### Add ROI index in node feautre

In [2]:
import numpy as np
import os
import pickle

In [9]:
list_file = open('/nasdata3/kyj/graphcl/GraphCL_Automated/ASD_test/x_pcc/file_list','r').read().split('\n')
list_file.pop()
list_file.pop(0)
print(list_file)


['pcc_ROISignals_28675.txt', 'pcc_ROISignals_28676.txt', 'pcc_ROISignals_28677.txt', 'pcc_ROISignals_28678.txt', 'pcc_ROISignals_28679.txt', 'pcc_ROISignals_28680.txt', 'pcc_ROISignals_28681.txt', 'pcc_ROISignals_28682.txt', 'pcc_ROISignals_28683.txt', 'pcc_ROISignals_28684.txt', 'pcc_ROISignals_28685.txt', 'pcc_ROISignals_28686.txt', 'pcc_ROISignals_28687.txt', 'pcc_ROISignals_28688.txt', 'pcc_ROISignals_28689.txt', 'pcc_ROISignals_28690.txt', 'pcc_ROISignals_28691.txt', 'pcc_ROISignals_28692.txt', 'pcc_ROISignals_28693.txt', 'pcc_ROISignals_28694.txt', 'pcc_ROISignals_28695.txt', 'pcc_ROISignals_28696.txt', 'pcc_ROISignals_28697.txt', 'pcc_ROISignals_28699.txt', 'pcc_ROISignals_28700.txt', 'pcc_ROISignals_28701.txt', 'pcc_ROISignals_28702.txt', 'pcc_ROISignals_28703.txt', 'pcc_ROISignals_28704.txt', 'pcc_ROISignals_28705.txt', 'pcc_ROISignals_28706.txt', 'pcc_ROISignals_28707.txt', 'pcc_ROISignals_28708.txt', 'pcc_ROISignals_28709.txt', 'pcc_ROISignals_28710.txt', 'pcc_ROISignals_287

In [7]:
with open('/nasdata4/mye/ADNI_graph_data/x_partialCC/pcc_ROISignals_136_S_4993.txt', 'r') as f:
    f = f.readlines()
    for i in range(len(f)):
        f[i] = f[i].rstrip('\n')
    l = [[float(num) for num in line.split(',')] for line in f]
arow = len(l)
acol = len(l[0])
#print(l)
#print("Rows : " + str(arow))
#print("Columns : " + str(acol))
print(l[0][115])

0.147448878343121


In [10]:
sub_list = []
for i in list_file:
        i=i.strip("pcc_ROISignals_")
        i=i.rstrip(".txt")
        sub_list.append(i)
print(len(sub_list))

703


In [11]:
#data = np.array(l[0])
one_hot = np.zeros((116,116))

rows = np.arange(116)
print(rows)

one_hot[rows,rows] = 1.0
print(one_hot)
print(len(one_hot))
print(len(one_hot[0]))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
116
116


In [12]:
for i in list_file:
    with open(f'/nasdata3/kyj/graphcl/GraphCL_Automated/ASD_test/x_pcc/{i}', 'r') as f:
        f = f.readlines()
        for j in range(len(f)):
            f[j] = f[j].rstrip('\n')
        l = [[float(num) for num in line.split(',')] for line in f]
    l = np.concatenate((l,one_hot),axis = 0)
    i = i.strip('pcc_ROISignals_')
    i = i.rstrip('.txt')
    np.savetxt(f'/nasdata3/kyj/graphcl/GraphCL_Automated/ASD_test/x_pcc_wth_idx/{i}.txt', l, fmt='%.15f', delimiter=',')
    #with open(f'/nasdata4/mye/ADNI_graph_data/x_pcc_with_idx/{i}.txt', 'wb') as f :
    #    f.write(l)
    #i = i.rstrip('.txt')
    #with open(f'/nasdata3/kyj/graphcl/GraphCL_Automated/HCP_data/x_roi_signal/{i}.pkl', 'wb') as f :
    #    pickle.dump(l, f)
print(l)

[[ 1.          0.321235    0.31510282 ...  0.15529648 -0.26583991
   0.06832216]
 [ 0.321235    1.         -0.16169382 ...  0.2712651  -0.15874562
  -0.38316641]
 [ 0.31510282 -0.16169382  1.         ... -0.14898008  0.20282168
  -0.08621369]
 ...
 [ 0.          0.          0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]
